
export const CountryCode = [
	{
		"id": 1 ,
		"name": "Sweden",
		"value": "+46",
		"countryCode": "SE",
		"icon" : "/flags/se.svg",
	},
	{
		"id": 2 ,
		"name": "United States of America",
		"value": "+1",
		"countryCode": "US",
		"icon": "/flags/us.svg",
	},
	{
	"id": 3 ,
	"name": "Canada",
	"value": "+1",
	"countryCode": "CA",
	"icon": "/flags/ca.svg"
	},
	{
	  "id": 4 ,
	  "name": "Afghanistan",
	  "value": "+93",
	  "countryCode": "AF",
	  "icon": "/flags/af.svg"
	},
	{
	  "id": 5 ,
	  "name": "Albania",
	  "value": "+355",
	  "countryCode": "AL",
	  "icon": "/flags/al.svg"
	},
	{
	  "id": 6 ,
	  "name": "Algeria",
	  "value": "+213",
	  "countryCode": "DZ",
	  "icon": "/flags/dz.svg"
	},
	{
	  "id": 7 ,
	  "name": "Angola",
	  "value": "+244",
	  "countryCode": "AO",
	  "icon": "/flags/ao.svg"
	},
	{
	  "id": 8 ,
	  "name": "Antigua and Barbuda",
	  "value": "+1268",
	  "countryCode": "AG",
	  "icon": "/flags/ag.svg"
	},
	{
	  "id": 9 ,
	  "name": "Argentina",
	  "value": "+54",
	  "countryCode": "AR",
	  "icon": "/flags/ar.svg"
	},
	{
	  "id": 10 ,
	  "name": "Armenia",
	  "value": "+374",
	  "countryCode": "AM",
	  "icon": "/flags/am.svg"
	},
	{
	  "id": 11 ,
	  "name": "Australia",
	  "value": "+61",
	  "countryCode": "AU",
	  "icon": "/flags/au.svg"
	},
	{
	  "id": 12,
	  "name": "Austria",
	  "value": "+43",
	  "countryCode": "AT",
	  "icon": "/flags/at.svg",
	},
	{
	  "id": 13,
	  "name": "Azerbaijan",
	  "value": "+994",
	  "countryCode": "AZ",
	  "icon": "/flags/az.svg",
	},
	{
	  "id": 14,
	  "name": "Bahamas",
	  "value": "+1242",
	  "countryCode": "BS",
	  "icon": "/flags/bs.svg",
	},
	{
	  "id": 15,
	  "name": "Bahrain",
	  "value": "+973",
	  "countryCode": "BH",
	  "icon": "/flags/bh.svg",
	},
	{
	  "id": 16,
	  "name": "Bangladesh",
	  "value": "+880",
	  "countryCode": "BD",
	  "icon": "/flags/bd.svg",
	},
	{
	  "id": 17,
	  "name": "Barbados",
	  "value": "+1246",
	  "countryCode": "BB",
	  "icon": "/flags/bb.svg",
	},
	{
	  "id": 18,
	  "name": "Belarus",
	  "value": "+375",
	  "countryCode": "BY",
	  "icon": "/flags/by.svg",
	},
	{
	  "id": 19,
	  "name": "Belgium",
	  "value": "+32",
	  "countryCode": "BE",
	  "icon": "/flags/be.svg",
	},
	{
	  "id": 20,
	  "name": "Belize",
	  "value": "+501",
	  "countryCode": "BZ",
	  "icon": "/flags/bz.svg",
	},
	{
	  "id": 21,
	  "name": "Benin",
	  "value": "+229",
	  "countryCode": "BJ",
	  "icon": "/flags/bj.svg",
	},
	{
	  "id": 22,
	  "name": "Bhutan",
	  "value": "+975",
	  "countryCode": "BT",
	  "icon": "/flags/bt.svg",
	},
	{
	  "id": 23,
	  "name": "Bolivia",
	  "value": "+591",
	  "countryCode": "BO",
	  "icon": "/flags/bo.svg",
	},
	{
	  "id": 24,
	  "name": "Bosnia and Herzegovina",
	  "value": "+387",
	  "countryCode": "BA",
	  "icon": "/flags/ba.svg",
	},
	{
	  "id": 25,
	  "name": "Botswana",
	  "value": "+267",
	  "countryCode": "BW",
	  "icon": "/flags/bw.svg",
	},
	{
	  "id": 26,
	  "name": "Brazil",
	  "value": "+55",
	  "countryCode": "BR",
	  "icon": "/flags/br.svg",
	},
	{
	  "id": 27,
	  "name": "Brunei",
	  "value": "+673",
	  "countryCode": "BN",
	  "icon": "/flags/bn.svg",
	},
	{
	  "id": 28,
	  "name": "Bulgaria",
	  "value": "+359",
	  "countryCode": "BG",
	  "icon": "/flags/bg.svg",
	},
	{
		"id": 29,
		"name": "Burkina Faso (Upper Volta)",
		"value": "+226",
		"countryCode": "BF",
		"icon": "/flags/bg.svg",
		"description": "Formerly known as Upper Volta until 1984."
	  },
	  {
		"id": 30,
		"name": "Burma",
		"value": "+95",
		"countryCode": "MM",
		"icon": "/flags/mm.svg",
		"description": "Now officially known as Myanmar."
	  },
	  {
		"id": 31,
		"name": "Burundi",
		"value": "+257",
		"countryCode": "BI",
		"icon": "/flags/bi.svg",
	  },



	  {
		"id": 32,
		"name": "Cabo Verde",
		"value": "+238",
		"countryCode": "CV",
		"icon": "/flags/cv.svg",
		"description": "Also known as Cape Verde."
	  },
	  {
		"id": 33,
		"name": "Cambodia",
		"value": "+855",
		"countryCode": "KH",
		"icon": "/flags/kh.svg"
	  },
	  {
		"id": 34,
		"name": "Cameroon",
		"value": "+237",
		"countryCode": "CM",
		"icon": "/flags/cm.svg"
	  },
	  {
		"id": 35,
		"name": "Cayman Islands, The",
		"value": "+1345",
		"countryCode": "KY",
		"icon": "/flags/ky.svg"
	  },
	  {
		"id": 36,
		"name": "Central African Republic",
		"value": "+236",
		"countryCode": "CF",
		"icon": "/flags/cg.svg"
	  },
	  {
		"id": 37,
		"name": "Chad",
		"value": "+235",
		"countryCode": "TD",
		"icon": "/flags/td.svg"
	  },
	  {
		"id": 38,
		"name": "Chile",
		"value": "+56",
		"countryCode": "CL",
		"icon": "/flags/cl.svg"
	  },
	  {
		"id": 39,
		"name": "China",
		"value": "+86",
		"countryCode": "CN",
		"icon": "/flags/cn.svg"
	  },
	  {
		"id": 40,
		"name": "Colombia",
		"value": "+57",
		"countryCode": "CO",
		"icon": "/flags/co.svg"
	  },
	  {
		"id": 41,
		"name": "Comoros",
		"value": "+269",
		"countryCode": "KM",
		"icon": "/flags/km.svg"
	  },
	  {
		"id": 42,
		"name": "Cook Islands",
		"value": "+682",
		"countryCode": "CK",
		"icon": "/flags/ck.svg"
	  },
	  {
		"id": 43,
		"name": "Costa Rica",
		"value": "+506",
		"countryCode": "CR",
		"icon": "/flags/cr.svg"
	  },
	  {
		"id": 44,
		"name": "Cote d’Ivoire (Ivory Coast)",
		"value": "+225",
		"countryCode": "CI",
		"icon": "/flags/ci.svg"
	  },
	  {
		"id": 45,
		"name": "Croatia",
		"value": "+385",
		"countryCode": "HR",
		"icon": "/flags/hr.svg"
	  },
	  {
		"id": 46,
		"name": "Cuba",
		"value": "+53",
		"countryCode": "CU",
		"icon": "/flags/cu.svg"
	  },
	  {
		"id": 47,
		"name": "Cyprus",
		"value": "+357",
		"countryCode": "CY",
		"icon": "/flags/cy.svg"
	  },
	  {
		"id": 48,
		"name": "Czechia",
		"value": "+420",
		"countryCode": "CZ",
		"icon": "/flags/cz.svg"
	  },
	  {
		"id": 49,
		"name": "Democratic Republic of the Congo",
		"value": "+243",
		"countryCode": "CD",
		"icon" : "/flags/cd.svg",
	  },
	  {
		"id": 50,
		"name": "Denmark",
		"value": "+45",
		"countryCode": "DK",
		"icon" : "/flags/dk.svg",
	  },
	  {
		"id": 51,
		"name": "Djibouti",
		"value": "+253",
		"countryCode": "DJ",
		"icon" : "/flags/dj.svg",
	  },
	  {
		"id": 52,
		"name": "Dominica",
		"value": "+1767",
		"countryCode": "DM",
		"icon" : "/flags/dm.svg",
	  },
	  {
		"id": 53,
		"name": "Dominican Republic",
		"value": "+1809",
		"countryCode": "DO",
		"icon" : "/flags/do.svg",
	  },
	  {
		"id": 54,
		"name": "Ecuador",
		"value": "+593",
		"countryCode": "EC",
		"icon" : "/flags/ec.svg",
	  },
	  {
		"id": 55,
		"name": "Egypt",
		"value": "+20",
		"countryCode": "EG",
		"icon" : "/flags/eg.svg",
	  },
	  {
		"id": 56,
		"name": "El Salvador",
		"value": "+503",
		"countryCode": "SV",
		"icon" : "/flags/sv.svg",
	  },
	  {
		"id": 57,
		"name": "Equatorial Guinea",
		"value": "+240",
		"countryCode": "GQ",
		"icon" : "/flags/gq.svg",
	  },
	  {
		"id": 58,
		"name": "Eritrea",
		"value": "+291",
		"countryCode": "ER",
		"icon" : "/flags/er.svg",
	  },
	  {
		"id": 59,
		"name": "Estonia",
		"value": "+372",
		"countryCode": "EE",
		"icon" : "/flags/ee.svg",
	  },
	  {
		"id": 60,
		"name": "Eswatini",
		"value": "+268",
		"countryCode": "SZ",
		"icon" : "/flags/sz.svg",
	  },
	  {
		"id": 61,
		"name": "Ethiopia",
		"value": "+251",
		"countryCode": "ET",
		"icon" : "/flags/et.svg",
	  },
	  {
		"id": 62,
		"name": "Fiji",
		"value": "+679",
		"countryCode": "FJ",
		"icon" : "/flags/fj.svg",
	  },
	  {
		"id": 63,
		"name": "Finland",
		"value": "+358",
		"countryCode": "FI",
		"icon" : "/flags/fi.svg",
	  },
	  {
		"id": 64,
		"name": "France",
		"value": "+33",
		"countryCode": "FR",
		"icon" : "/flags/fr.svg",
	  },
	  {
		"id": 65,
		"name": "Gabon",
		"value": "+241",
		"countryCode": "GA",
		"icon" : "/flags/ga.svg",
	  },
	  {
		"id": 66,
		"name": "Gambia, The",
		"value": "+220",
		"countryCode": "GM",
		"icon" : "/flags/gm.svg",
	  },
	  {
		"id": 67,
		"name": "Germany",
		"value": "+49",
		"countryCode": "DE",
		"icon" : "/flags/de.svg",
	  },
	  {
		"id": 68,
		"name": "Ghana",
		"value": "+233",
		"countryCode": "GH",
		"icon" : "/flags/gh.svg",
	  },
	  {
		"id": 69,
		"name": "Greece",
		"value": "+30",
		"countryCode": "GR",
		"icon" : "/flags/gr.svg",
	  },
	  {
		"id": 70,
		"name": "Grenada",
		"value": "+1473",
		"countryCode": "GD",
		"icon" : "/flags/gd.svg",
	  },
	  {
		"id": 71,
		"name": "Guatemala",
		"value": "+502",
		"countryCode": "GT",
		"icon" : "/flags/gt.svg",
	  },
	  {
		"id": 72,
		"name": "Guinea",
		"value": "+224",
		"countryCode": "GN",
		"icon" : "/flags/gn.svg",
	  },
	  {
		"id": 73,
		"name": "Guinea-Bissau",
		"value": "+245",
		"countryCode": "GW",
		"icon" : "/flags/gw.svg",
	  },
	  {
		"id": 74,
		"name": "Guyana",
		"value": "+592",
		"countryCode": "GY",
		"icon" : "/flags/gy.svg",
	  },
	  {
		"id": 75,
		"name": "Haiti",
		"value": "+509",
		"countryCode": "HT",
		"icon" : "/flags/ht.svg",
	  },
	  {
		"id": 76,
		"name": "Holy See",
		"value": "+39",
		"countryCode": "VA",
		"icon" : "/flags/va.svg",
	  },
	  {
		"id": 77,
		"name": "Honduras",
		"value": "+504",
		"countryCode": "HN",
		"icon" : "/flags/hn.svg",
	  },
	  {
		"id": 78,
		"name": "Hungary",
		"value": "+36",
		"countryCode": "HU",
		"icon" : "/flags/hu.svg",
	  },
	  {
		"id": 79,
		"name": "Iceland",
		"value": "+354",
		"countryCode": "IS",
		"icon" : "/flags/is.svg",
	  },
	  {
		"id": 80,
		"name": "India",
		"value": "+91",
		"countryCode": "IN",
		"icon" : "/flags/in.svg",
	  },
	  {
		"id": 81,
		"name": "Indonesia",
		"value": "+62",
		"countryCode": "ID",
		"icon" : "/flags/id.svg",
	  },
	  {
		"id": 82,
		"name": "Iran",
		"value": "+98",
		"countryCode": "IR",
		"icon" : "/flags/ir.svg",
	  },
	  {
		"id": 83,
		"name": "Iraq",
		"value": "+964",
		"countryCode": "IQ",
		"icon" : "/flags/iq.svg",
	  },
	  {
		"id": 84,
		"name": "Ireland",
		"value": "+353",
		"countryCode": "IE",
		"icon" : "/flags/ie.svg",
	  },
	  {
		"id": 85,
		"name": "Italy",
		"value": "+39",
		"countryCode": "IT",
		"icon" : "/flags/it.svg",
	  },
	  {
		"id": 86,
		"name": "Jamaica",
		"value": "+1876",
		"countryCode": "JM",
		"icon" : "/flags/jm.svg",
	  },
	  {
		"id": 87,
		"name": "Japan",
		"value": "+81",
		"countryCode": "JP",
		"icon" : "/flags/jp.svg",
	  },
	  {
		"id": 88,
		"name": "Jordan",
		"value": "+962",
		"countryCode": "JO",
		"icon" : "/flags/jo.svg",
	  },
	  {
		"id": 89 ,
		"name": "Kazakhstan",
		"value": "+7",
		"countryCode": "KZ",
		"icon" : "/flags/kz.svg",
	  },
	  {
		"id": 90 ,
		"name": "Kenya",
		"value": "+254",
		"countryCode": "KE",
		"icon" : "/flags/ke.svg",
	  },
	  {
		"id": 91 ,
		"name": "Kiribati",
		"value": "+686",
		"countryCode": "KI",
		"icon" : "/flags/ki.svg",
	  },
	  {
		"id": 92 ,
		"name": "Korea",
		"value": "+82",
		"countryCode": "KR",
		"icon" : "/flags/kr.svg",
	  },
	  {
		"id": 93 ,
		"name": "Kosovo",
		"value": "+383",
		"countryCode": "XK",
		"icon" : "/flags/xk.svg",
	  },
	  {
		"id": 94 ,
		"name": "Kuwait",
		"value": "+965",
		"countryCode": "KW",
		"icon" : "/flags/kw.svg",
	  },
	  {
		"id": 95 ,
		"name": "Kyrgyzstan",
		"value": "+996",
		"countryCode": "KG",
		"icon" : "/flags/kg.svg",
	  },
	  {
		"id": 96 ,
		"name": "Laos",
		"value": "+856",
		"countryCode": "LA",
		"icon" : "/flags/la.svg",
	  },
	  {
		"id": 97 ,
		"name": "Latvia",
		"value": "+371",
		"countryCode": "LV",
		"icon" : "/flags/lv.svg",
	  },
	  {
		"id": 98 ,
		"name": "Lebanon",
		"value": "+961",
		"countryCode": "LB",
		"icon" : "/flags/lb.svg",
	  },
	  {
		"id": 99 ,
		"name": "Lesotho",
		"value": "+266",
		"countryCode": "LS",
		"icon" : "/flags/ls.svg",
	  },
	  {
		"id": 100 ,
		"name": "Liberia",
		"value": "+231",
		"countryCode": "LR",
		"icon" : "/flags/lr.svg",
	  },
	  {
		"id": 101 ,
		"name": "Libya",
		"value": "+218",
		"countryCode": "LY",
		"icon" : "/flags/ly.svg",
	  },
	  {
		"id": 102 ,
		"name": "Liechtenstein",
		"value": "+423",
		"countryCode": "LI",
		"icon" : "/flags/li.svg",
	  },
	  {
		"id": 103 ,
		"name": "Lithuania",
		"value": "+370",
		"countryCode": "LT",
		"icon" : "/flags/lt.svg",
	  },
	  {
		"id": 104 ,
		"name": "Luxembourg",
		"value": "+352",
		"countryCode": "LU",
		"icon" : "/flags/lu.svg",
	  },
	  {
		"id": 105 ,
		"name": "Madagascar",
		"value": "+261",
		"countryCode": "MG",
		"icon" : "/flags/mg.svg",
	  },
	  {
		"id": 106 ,
		"name": "Malawi",
		"value": "+265",
		"countryCode": "MW",
		"icon" : "/flags/mw.svg",
	  },
	  {
		"id": 107 ,
		"name": "Malaysia",
		"value": "+60",
		"countryCode": "MY",
		"icon" : "/flags/my.svg",
	  },
	  {
		"id": 108 ,
		"name": "Maldives",
		"value": "+960",
		"countryCode": "MV",
		"icon" : "/flags/mv.svg",
	  },
	  {
		"id": 109 ,
		"name": "Mali",
		"value": "+223",
		"countryCode": "ML",
		"icon" : "/flags/ml.svg",
	  },
	  {
		"id": 110 ,
		"name": "Malta",
		"value": "+356",
		"countryCode": "MT",
		"icon" : "/flags/mt.svg",
	  },
	  {
		"id": 111 ,
		"name": "Marshall Islands",
		"value": "+692",
		"countryCode": "MH",
		"icon" : "/flags/mh.svg",
	  },
	  {
		"id": 112 ,
		"name": "Mauritania",
		"value": "+222",
		"countryCode": "MR",
		"icon" : "/flags/mr.svg",
	  },
	  {
		"id": 113 ,
		"name": "Mauritius",
		"value": "+230",
		"countryCode": "MU",
		"icon" : "/flags/mu.svg",
	  },
	  {
		"id": 114 ,
		"name": "Mexico",
		"value": "+52",
		"countryCode": "MX",
		"icon" : "/flags/mx.svg",
	  },
	  {
		"id": 115 ,
		"name": "Micronesia",
		"value": "+691",
		"countryCode": "FM",
		"icon" : "/flags/fm.svg",
	  },
	  {
		"id": 116 ,
		"name": "Moldova",
		"value": "+373",
		"countryCode": "MD",
		"icon" : "/flags/md.svg",
	  },
	  {
		"id": 117 ,
		"name": "Monaco",
		"value": "+377",
		"countryCode": "MC",
		"icon" : "/flags/mc.svg",
	  },
	  {
		"id": 118 ,
		"name": "Mongolia",
		"value": "+976",
		"countryCode": "MN",
		"icon" : "/flags/mn.svg",
	  },
	  {
		"id": 119 ,
		"name": "Montenegro",
		"value": "+382",
		"countryCode": "ME",
		"icon" : "/flags/me.svg",
	  },
	  {
		"id": 120 ,
		"name": "Morocco",
		"value": "+212",
		"countryCode": "MA",
		"icon" : "/flags/ma.svg",
	  },
	  {
		"id": 121 ,
		"name": "Mozambique",
		"value": "+258",
		"countryCode": "MZ",
		"icon" : "/flags/mz.svg",
	  },
	  {
		"id": 122 ,
		"name": "Namibia",
		"value": "+264",
		"countryCode": "NA",
		"icon" : "/flags/na.svg",
	  },
	  {
		"id": 123 ,
		"name": "Nauru",
		"value": "+674",
		"countryCode": "NR",
		"icon" : "/flags/nr.svg",
	  },
	  {
		"id": 124 ,
		"name": "Nepal",
		"value": "+977",
		"countryCode": "NP",
		"icon" : "/flags/np.svg",
	  },
	  {
		"id": 125 ,
		"name": "Netherlands, The",
		"value": "+31",
		"countryCode": "NL",
		"icon" : "/flags/nl.svg",
	  },
	  {
		"id": 126 ,
		"name": "New Zealand",
		"value": "+64",
		"countryCode": "NZ",
		"icon" : "/flags/nz.svg",
	  },
	  {
		"id": 127 ,
		"name": "Nicaragua",
		"value": "+505",
		"countryCode": "NI",
		"icon" : "/flags/ni.svg",
	  },
	  {
		"id": 128 ,
		"name": "Niger",
		"value": "+227",
		"countryCode": "NE",
		"icon" : "/flags/ne.svg",
	  },
	  {
		"id": 129 ,
		"name": "Nigeria",
		"value": "+234",
		"countryCode": "NG",
		"icon" : "/flags/ng.svg",
	  },
	  {
		"id": 130 ,
		"name": "Niue",
		"value": "+683",
		"countryCode": "NU",
		"icon" : "/flags/nu.svg",
	  },
	  {
		"id": 131 ,
		"name": "North Macedonia",
		"value": "+389",
		"countryCode": "MK",
		"icon" : "/flags/mk.svg",
	  },
	  {
		"id": 132 ,
		"name": "Norway",
		"value": "+47",
		"countryCode": "NO",
		"icon" : "/flags/no.svg",
	  },
	  {
		"id": 133 ,
		"name": "Oman",
		"value": "+968",
		"countryCode": "OM",
		"icon" : "/flags/om.svg",
	  },
	  {
		"id": 134 ,
		"name": "Pakistan",
		"value": "+92",
		"countryCode": "PK",
		"icon" : "/flags/pk.svg",
	  },
	  {
		"id": 135 ,
		"name": "Palau",
		"value": "+680",
		"countryCode": "PW",
		"icon" : "/flags/pw.svg",
	  },
	  {
		"id": 136 ,
		"name": "Panama",
		"value": "+507",
		"countryCode": "PA",
		"icon" : "/flags/pa.svg",
	  },
	  {
		"id": 137 ,
		"name": "Papua New Guinea",
		"value": "+675",
		"countryCode": "PG",
		"icon" : "/flags/pg.svg",
	  },
	  {
		"id": 138 ,
		"name": "Paraguay",
		"value": "+595",
		"countryCode": "PY",
		"icon" : "/flags/py.svg",
	  },
	  {
		"id": 139 ,
		"name": "Peru",
		"value": "+51",
		"countryCode": "PE",
		"icon" : "/flags/pe.svg",
	  },
	  {
		"id": 140 ,
		"name": "Philippines",
		"value": "+63",
		"countryCode": "PH",
		"icon" : "/flags/ph.svg",
	  },
	  {
		"id": 141 ,
		"name": "Poland",
		"value": "+48",
		"countryCode": "PL",
		"icon" : "/flags/pl.svg",
	  },
	  {
		"id": 142 ,
		"name": "Portugal",
		"value": "+351",
		"countryCode": "PT",
		"icon" : "/flags/pt.svg",
	  },
	  {
		"id": 143 ,
		"name": "Qatar",
		"value": "+974",
		"countryCode": "QA",
		"icon" : "/flags/qa.svg",
	  },
	  {
		"id": 144 ,
		"name": "Republic of Korea (South Korea)",
		"value": "+82",
		"countryCode": "KR",
		"icon" : "/flags/kr.svg",
	  },
	  {
		"id": 145 ,
		"name": "Republic of the Congo",
		"value": "+242",
		"countryCode": "CG",
		"icon" : "/flags/cg.svg",
	  },
	  {
		"id": 146 ,
		"name": "Romania",
		"value": "+40",
		"countryCode": "RO",
		"icon" : "/flags/ro.svg",
	  },
	  {
		"id": 147 ,
		"name": "Russia",
		"value": "+7",
		"countryCode": "RU",
		"icon" : "/flags/ru.svg",
	  },
	  {
		"id": 148 ,
		"name": "Rwanda",
		"value": "+250",
		"countryCode": "RW",
		"icon" : "/flags/rw.svg",
	  },
	  {
		"id": 149 ,
		"name": "Saint Kitts and Nevis",
		"value": "+1869",
		"countryCode": "KN",
		"icon" : "/flags/kn.svg",
	  },
	  {
		"id": 150 ,
		"name": "Saint Lucia",
		"value": "+1758",
		"countryCode": "LC",
		"icon" : "/flags/lc.svg",
	  },
	  {
		"id": 151 ,
		"name": "Saint Vincent and the Grenadines",
		"value": "+1784",
		"countryCode": "VC",
		"icon" : "/flags/vc.svg",
	  },
	  {
		"id": 152 ,
		"name": "Samoa",
		"value": "+685",
		"countryCode": "WS",
		"icon" : "/flags/ws.svg",
	  },
	  {
		"id": 153 ,
		"name": "San Marino",
		"value": "+378",
		"countryCode": "SM",
		"icon" : "/flags/sm.svg",
	  },
	  {
		"id": 154 ,
		"name": "Sao Tome and Principe",
		"value": "+239",
		"countryCode": "ST",
		"icon" : "/flags/st.svg",
	  },
	  {
		"id": 155 ,
		"name": "Saudi Arabia",
		"value": "+966",
		"countryCode": "SA",
		"icon" : "/flags/sa.svg",
	  },
	  {
		"id": 156 ,
		"name": "Senegal",
		"value": "+221",
		"countryCode": "SN",
		"icon" : "/flags/sn.svg",
	  },
	  {
		"id": 157 ,
		"name": "Serbia",
		"value": "+381",
		"countryCode": "RS",
		"icon" : "/flags/rs.svg",
	  },
	  {
		"id": 158 ,
		"name": "Seychelles",
		"value": "+248",
		"countryCode": "SC",
		"icon" : "/flags/sc.svg",
	  },
	  {
		"id": 159 ,
		"name": "Sierra Leone",
		"value": "+232",
		"countryCode": "SL",
		"icon" : "/flags/sl.svg",
	  },
	  {
		"id": 160 ,
		"name": "Singapore",
		"value": "+65",
		"countryCode": "SG",
		"icon" : "/flags/sg.svg",
	  },
	  {
		"id": 161 ,
		"name": "Slovakia",
		"value": "+421",
		"countryCode": "SK",
		"icon" : "/flags/sk.svg",
	  },
	  {
		"id": 162 ,
		"name": "Slovenia",
		"value": "+386",
		"countryCode": "SI",
		"icon" : "/flags/si.svg",
	  },
	  {
		"id": 163 ,
		"name": "Solomon Islands",
		"value": "+677",
		"countryCode": "SB",
		"icon" : "/flags/sb.svg",
	  },
	  {
		"id": 164 ,
		"name": "Somalia",
		"value": "+252",
		"countryCode": "SO",
		"icon" : "/flags/so.svg",
	  },
	  {
		"id": 165 ,
		"name": "South Africa",
		"value": "+27",
		"countryCode": "ZA",
		"icon" : "/flags/za.svg",
	  },
	  {
		"id": 166 ,
		"name": "South Sudan",
		"value": "+211",
		"countryCode": "SS",
		"icon" : "/flags/ss.svg",
	  },
	  {
		"id": 167 ,
		"name": "Spain",
		"value": "+34",
		"countryCode": "ES",
		"icon" : "/flags/es.svg",
	  },
	  {
		"id": 168 ,
		"name": "Sri Lanka",
		"value": "+94",
		"countryCode": "LK",
		"icon" : "/flags/lk.svg",
	  },
	  {
		"id": 169 ,
		"name": "Sudan",
		"value": "+249",
		"countryCode": "SD",
		"icon" : "/flags/sd.svg",
	  },
	  {
		"id": 170 ,
		"name": "Suriname",
		"value": "+597",
		"countryCode": "SR",
		"icon" : "/flags/sr.svg",
	  },
	  {
		"id": 171 ,
		"name": "Switzerland",
		"value": "+41",
		"countryCode": "CH",
		"icon" : "/flags/ch.svg",
	  },
	  {
		"id": 172 ,
		"name": "Syria",
		"value": "+963",
		"countryCode": "SY",
		"icon" : "/flags/sy.svg",
	  },
	  {
		"id": 173 ,
		"name": "Tajikistan",
		"value": "+992",
		"countryCode": "TJ",
		"icon" : "/flags/tj.svg",
	  },
	  {
		"id": 174 ,
		"name": "Tanzania",
		"value": "+255",
		"countryCode": "TZ",
		"icon" : "/flags/tz.svg",
	  },
	  {
		"id": 175 ,
		"name": "Thailand",
		"value": "+66",
		"countryCode": "TH",
		"icon" : "/flags/th.svg",
	  },
	  {
		"id": 176 ,
		"name": "Timor-Leste",
		"value": "+670",
		"countryCode": "TL",
		"icon" : "/flags/tl.svg",
	  },
	  {
		"id": 177 ,
		"name": "Togo",
		"value": "+228",
		"countryCode": "TG",
		"icon" : "/flags/tg.svg",
	  },
	  {
		"id": 178 ,
		"name": "Tonga",
		"value": "+676",
		"countryCode": "TO",
		"icon" : "/flags/to.svg",
	  },
	  {
		"id": 179 ,
		"name": "Trinidad and Tobago",
		"value": "+1868",
		"countryCode": "TT",
		"icon" : "/flags/tt.svg",
	  },
	  {
		"id": 180 ,
		"name": "Tunisia",
		"value": "+216",
		"countryCode": "TN",
		"icon" : "/flags/tn.svg",
	  },
	  {
		"id": 181 ,
		"name": "Turkey",
		"value": "+90",
		"countryCode": "TR",
		"icon" : "/flags/tr.svg",
	  },
	  {
		"id": 182 ,
		"name": "Turkmenistan",
		"value": "+993",
		"countryCode": "TM",
		"icon" : "/flags/tm.svg",
	  },
	  {
		"id": 183 ,
		"name": "Tuvalu",
		"value": "+688",
		"countryCode": "TV",
		"icon" : "/flags/tv.svg",
	  },
	  {
		"id": 184 ,
		"name": "Uganda",
		"value": "+256",
		"countryCode": "UG",
		"icon" : "/flags/ug.svg",
	  },
	  {
		"id": 185 ,
		"name": "Ukraine",
		"value": "+380",
		"countryCode": "UA",
		"icon" : "/flags/ua.svg",
	  },
	  {
		"id": 186 ,
		"name": "United Arab Emirates, The",
		"value": "+971",
		"countryCode": "AE",
		"icon" : "/flags/ae.svg",
	  },
	  {
		"id": 187 ,
		"name": "United Kingdom, The",
		"value": "+44",
		"countryCode": "GB",
		"icon" : "/flags/gb.svg",
	  },
	  {
		"id": 188 ,
		"name": "Uruguay",
		"value": "+598",
		"countryCode": "UY",
		"icon" : "/flags/uy.svg",
	  },
	  {
		"id": 189 ,
		"name": "Uzbekistan",
		"value": "+998",
		"countryCode": "UZ",
		"icon" : "/flags/uz.svg",
	  },
	  {
		"id": 190 ,
		"name": "Vanuatu",
		"value": "+678",
		"countryCode": "VU",
		"icon" : "/flags/vu.svg",
	  },
	  {
		"id": 191 ,
		"name": "Venezuela",
		"value": "+58",
		"countryCode": "VE",
		"icon" : "/flags/ve.svg",
	  },
	  {
		"id": 192 ,
		"name": "Vietnam",
		"value": "+84",
		"countryCode": "VN",
		"icon" : "/flags/vn.svg",
	  },
	  {
		"id": 193 ,
		"name": "Württemberg",
		"value": "+49",
		"countryCode": "DE",
		"icon" : "/flags/de.svg",
		"description": "Historical kingdom in Germany (1806–1918)."
	  },
	  {
		"id": 194 ,
		"name": "Yemen",
		"value": "+967",
		"countryCode": "YE",
		"icon" : "/flags/ye.svg",
	  },
	  {
		"id": 195 ,
		"name": "Zambia",
		"value": "+260",
		"countryCode": "ZM",
		"icon" : "/flags/zm.svg",
	  },
	  {
		"id": 196 ,
		"name": "Zimbabwe",
		"value": "+263",
		"countryCode": "ZW",
		"icon" : "/flags/zw.svg",
	  }
  ]